### ISSUE TITLE
ImportError: No module named 'docsbox.settings'

### ISSUE THREAD

**Issue by ConradIrwin** [dveselov/docsbox#2]
I tried running this with `docker-compose build` and `docker-compose up`, but I'm seeing this error message repeated many times. Did I miss creating a configuration file?

```
web_1          | [2018-01-30 07:55:32 +0000] [1] [INFO] Starting gunicorn 19.6.0
web_1          | [2018-01-30 07:55:32 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
web_1          | [2018-01-30 07:55:32 +0000] [1] [INFO] Using worker: sync
web_1          | [2018-01-30 07:55:32 +0000] [7] [INFO] Booting worker with pid: 7
web_1          | Failed to find application: 'docsbox'
web_1          | [2018-01-30 07:55:32 +0000] [7] [INFO] Worker exiting (pid: 7)
web_1          | [2018-01-30 07:55:32 +0000] [1] [INFO] Shutting down: Master
web_1          | [2018-01-30 07:55:32 +0000] [1] [INFO] Reason: App failed to load.
rqworker_1     | Traceback (most recent call last):
rqworker_1     |   File "/usr/local/bin/rq", line 9, in <module>
rqworker_1     |     load_entry_point('rq==0.10.0', 'console_scripts', 'rq')()
rqworker_1     |   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
rqworker_1     |     return self.main(*args, **kwargs)
rqworker_1     |   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
rqworker_1     |     rv = self.invoke(ctx)
rqworker_1     |   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
rqworker_1     |     return _process_result(sub_ctx.command.invoke(sub_ctx))
rqworker_1     |   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
rqworker_1     |     return ctx.invoke(self.callback, **ctx.params)
rqworker_1     |   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
rqworker_1     |     return callback(*args, **kwargs)
rqworker_1     |   File "/usr/local/lib/python3.5/dist-packages/rq/cli/cli.py", line 73, in wrapper
rqworker_1     |     return ctx.invoke(func, cli_config, *args[1:], **kwargs)
rqworker_1     |   File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
rqworker_1     |     return callback(*args, **kwargs)
rqworker_1     |   File "/usr/local/lib/python3.5/dist-packages/rq/cli/cli.py", line 189, in worker
rqworker_1     |     settings = read_config_file(cli_config.config) if cli_config.config else {}
rqworker_1     |   File "/usr/local/lib/python3.5/dist-packages/rq/cli/helpers.py", line 27, in read_config_file
rqworker_1     |     settings = importlib.import_module(module)
rqworker_1     |   File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
rqworker_1     |     return _bootstrap._gcd_import(name[level:], package, level)
rqworker_1     |   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
rqworker_1     |   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
rqworker_1     |   File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
rqworker_1     | ImportError: No module named 'docsbox.settings'
```

**Comment by rafalkasa** [comment]
Hi, I have exactly the same issue, any solution for that ?
This issue only occur on Windows 10 machine, everything is working fine on ubuntu 16_04

**Comment by sujitsakre** [comment]
Hi, we had the same issue on the windows 10 machine. You need to modify your docker-compose.yml file. e.g. 

web:
  restart: always
  build: .\docsbox
  expose:
    - "8000"
  links:
    - redis:redis
  volumes:
    - c:\users\xyz\desktop\docsbox\docsbox:/home/docsbox
    - c:\users\xyz\desktop\docsbox\media:/home/docsbox/media
    - c:\xampp\htdocs:/home/docsbox/web
  command: gunicorn -b :8000 docsbox:app

rqworker:
  restart: always
  build: .\docsbox
  links:
    - redis:redis
  volumes_from:
    - web
  command: rq worker -c docsbox.settings

rqscheduler:
